# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170129_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(default='ADD SURNAME', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='trivia',
            field=models.TextField(blank=True, help_text='Any related facts or trivia relating to this movie', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='youtubeid',
            field=models.CharField(blank=True, help_text='Unique youtube video id for the trailer <a href="https://www.isbn-international.org/content/what-isbn">Youtube ID</a>', max_length=40, null=True, verbose_name='Youtube ID'),
        ),
    ]
