# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='bio',
            field=models.TextField(default='No Bio Information Set', help_text='Enter a brief Character Bio or Resume', max_length=1000),
        ),
    ]
